# Enable reflection true is similar to the swagger in rest
spring:
  grpc:
    server:
      ssl:
        enabled: false
        bundle: web-server
      port: 9090
      reflection:
        enabled: true


app:
  custom-message: ${MY_CUSTOM_MESSAGE:default-message}